-- REPORT 수정 전 전체 데이터 저장
CREATE TABLE TB_REPORT_HISTORY ENGINE = InnoDB AS
SELECT *
FROM TB_REPORT
WHERE 1 = 0;

ALTER TABLE TB_REPORT_HISTORY
    CHANGE COLUMN id reportId INT NOT NULL,
    ADD COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
    ADD COLUMN status VARCHAR(20) NOT NULL AFTER reportId,
    ADD COLUMN userId VARCHAR(100) NOT NULL AFTER status,
    ADD COLUMN modifiedAt DATETIME(6) NOT NULL AFTER userId,
    ADD PRIMARY KEY (id),
    ADD INDEX IDX_REPORT_HISTORY_REPORT (reportId, id);


-- PENETRATION 수정 전 전체 데이터 저장
CREATE TABLE TB_PENETRATION_HISTORY ENGINE = InnoDB AS
SELECT *
FROM TB_PENETRATION
WHERE 1 = 0;

ALTER TABLE TB_PENETRATION_HISTORY
    CHANGE COLUMN id penetrationId INT NOT NULL,
    ADD COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
    ADD COLUMN reportHistoryId BIGINT UNSIGNED NOT NULL AFTER id,
    ADD PRIMARY KEY (id),
    ADD INDEX IDX_PENETRATION_HISTORY_REPORT_HISTORY (reportHistoryId);


-- PIECE 수정 전 전체 데이터 저장
CREATE TABLE TB_PIECE_HISTORY ENGINE = InnoDB AS
SELECT *
FROM TB_PIECE
WHERE 1 = 0;

ALTER TABLE TB_PIECE_HISTORY
    CHANGE COLUMN id pieceId INT NOT NULL,
    ADD COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
    ADD COLUMN reportHistoryId BIGINT UNSIGNED NOT NULL AFTER id,
    ADD PRIMARY KEY (id),
    ADD INDEX IDX_PIECE_HISTORY_REPORT_HISTORY (reportHistoryId);