-- REPORT 수정 전 전체 데이터 저장
CREATE TABLE TB_REPORT_HISTORY AS
SELECT *
FROM TB_REPORT
WHERE 1 = 0;

ALTER TABLE TB_REPORT_HISTORY
    CHANGE COLUMN id reportId INT NOT NULL,
    ADD COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
    ADD COLUMN status VARCHAR(20) NOT NULL AFTER reportId,
    ADD COLUMN userId VARCHAR(100) NOT NULL AFTER status,
    ADD COLUMN modifiedAt DATETIME NOT NULL AFTER userId,
    ADD PRIMARY KEY (id),
    ADD INDEX IDX_REPORT_HISTORY_REPORT (reportId, id);


-- PENETRATION 수정 전 데이터 저장 (피벗 1행 구조)
CREATE TABLE TB_PENETRATION_HISTORY (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reportHistoryId BIGINT UNSIGNED NOT NULL,
    penetrationId INT NOT NULL,
    reportIdx INT NOT NULL,
    p1 VARCHAR(20),
    p2 VARCHAR(20),
    p3 VARCHAR(20),
    p4 VARCHAR(20),
    p5 VARCHAR(20),
    p6 VARCHAR(20),
    p7 VARCHAR(20),
    p8 VARCHAR(20),
    p9 VARCHAR(20),
    p10 VARCHAR(20),
    PRIMARY KEY (id),
    INDEX IDX_PENETRATION_HISTORY_REPORT_HISTORY (reportHistoryId)
);


-- PIECE 수정 전 데이터 저장 (피벗 1행 구조)
CREATE TABLE TB_PIECE_HISTORY (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    reportHistoryId BIGINT UNSIGNED NOT NULL,
    reportIdx INT NOT NULL,
    singleLevel VARCHAR(50),
    topLevel VARCHAR(50),
    middleLevel VARCHAR(200),
    bottomLevel VARCHAR(50),
    PRIMARY KEY (id),
    INDEX IDX_PIECE_HISTORY_REPORT_HISTORY (reportHistoryId)
);